### PR TITLE
Add base option, dynamic load option and convenience methods

### PR DESCRIPTION
**Pull request by llun**

### CODE REVIEW

**Comment by yosssi** [comment]
@llun Wow, thanks for your careful work! I have a question:

Why do you want the `Ace` method? I think the `HTML` method is enough. Do you think that specifying `*ace.Options` every time calling the `HTML` method is troublesome? If so, that's fault of Ace and I will consider adding a function which enables us to set global options to Ace.

**Comment by llun** [comment]
@yosssi I don't think it's Ace fault to do it in this way but using with web framework it's troublesome because usually web will have a few template files (one per page + base layout) and don't put it in root directory. So for HTML it will need `path/to/template/template:path/to/base/template` in all pages.

For `Ace` method, It can merge to HTML but I created a new one so user have an option to change `*ace.Options` per request.

**Comment by yosssi** [comment]
@llun Thanks for your reply! Please give me time to think about which structure of Ace / Acerender is best for web developers. Thanks!

**Comment by yosssi** [comment]
@llun Hi,

Sorry for the late reply.

I decided to add a function which enables us to set global options to Ace & Martini Acerender.

Please check the following part of the README.md.

https://github.com/yosssi/martini-acerender#ace-options

Thanks for your valuable PR and comments!

If you have any idea or requests, please feel free to create an issue or send a PR!

**Pull request closed without merging**
